export const CATEGORIES = [
  { id: "food", label: "Food & Drinks", icon: "🍜" },
  { id: "groceries", label: "Groceries", icon: "🛒" },
  { id: "transport", label: "Transportation", icon: "🚌" },
  { id: "shopping", label: "Shopping", icon: "🛍️" },
  { id: "bills", label: "Bills & Rent", icon: "🧾" },
  { id: "entertainment", label: "Fun & Entertainment", icon: "🎬" },
  { id: "health", label: "Health & Care", icon: "💊" },
  { id: "other", label: "Other", icon: "📦" },
] as const;

export type CategoryId = (typeof CATEGORIES)[number]["id"];

export const FOOD_CATEGORY: CategoryId = "food";
export const SIMPLE_BUDGET_CATEGORIES = CATEGORIES.filter((c) => c.id !== FOOD_CATEGORY);

export const categoryLabel = (id: CategoryId) =>
  CATEGORIES.find((c) => c.id === id)?.label ?? id;
export const categoryIcon = (id: CategoryId) =>
  CATEGORIES.find((c) => c.id === id)?.icon ?? "📦";

export interface Expense {
  id: string;
  name: string | null;
  amount: number;        // integer IDR
  categoryId: CategoryId;
  occurredAt: number;    // epoch ms — the date it happened (budgets use this)
  createdAt: number;     // epoch ms
  updatedAt: number;     // epoch ms — LWW key
  deleted: boolean;      // soft delete
  recurringRuleId?: string; // set when auto-generated by a recurring rule
}

export interface SimpleBudget {
  categoryId: CategoryId; // keyPath; never "food"
  monthlyAmount: number;
  updatedAt: number;
  deleted: boolean;
}

export type SplitMode = "even" | "split";

export interface FoodBudget {
  id: "foodBudget";
  splitMode: SplitMode;
  weekdayAmount: number; // daily rupiah for weekdays (and THE daily amount when "even")
  weekendAmount: number; // daily rupiah for weekends (equals weekdayAmount when "even")
  updatedAt: number;
  deleted: boolean;
}

export type RecurringFrequency = "monthly" | "weekly" | "cycle";

export interface RecurringRule {
  id: string;
  name: string | null;
  amount: number;              // integer IDR
  categoryId: CategoryId;
  frequency: RecurringFrequency;
  dayOfMonth?: number;         // 1..28 — used when frequency === "monthly"
  weekday?: number;            // 0=Sun..6=Sat — used when frequency === "weekly"
  // "cycle" needs no anchor — it fires on settings.cycleStartDay each cycle
  startAt: number;             // epoch ms — never materialize occurrences before this
  lastRunAt: number | null;    // epoch ms of the latest occurrence already created (null = none yet)
  createdAt: number;
  updatedAt: number;           // LWW key
  deleted: boolean;
}

export type FoodReset = "daily" | "weekly" | "cycle";

export interface Settings {
  id: "settings";         // singleton
  cycleStartDay: number;  // 1..28, your payroll anchor
  foodRollover: boolean;  // legacy mirror of foodReset (kept in sync for older clients)
  foodReset?: FoodReset;  // daily = fixed per day, weekly = Mon-reset, cycle = cycle-reset
  updatedAt: number;
  deleted: boolean;
}